version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dari_postgres
    environment:
      POSTGRES_DB: dari_wallet_v2
      POSTGRES_USER: dari_user
      POSTGRES_PASSWORD: dari_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dari_user -d dari_wallet_v2"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: dari_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: dari_api
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://dari_user:dari_password@db:5432/dari_wallet_v2
      - DATABASE_URL_SYNC=postgresql://dari_user:dari_password@db:5432/dari_wallet_v2
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key
      - ENVIRONMENT=development
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - dari_network

  celery_worker:
    build: .
    container_name: dari_celery_worker
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://dari_user:dari_password@db:5432/dari_wallet_v2
      - DATABASE_URL_SYNC=postgresql://dari_user:dari_password@db:5432/dari_wallet_v2
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - dari_network

  celery_beat:
    build: .
    container_name: dari_celery_beat
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://dari_user:dari_password@db:5432/dari_wallet_v2
      - DATABASE_URL_SYNC=postgresql://dari_user:dari_password@db:5432/dari_wallet_v2
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - dari_network

  flower:
    build: .
    container_name: dari_flower
    command: celery -A app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://dari_user:dari_password@db:5432/dari_wallet_v2
      - DATABASE_URL_SYNC=postgresql://dari_user:dari_password@db:5432/dari_wallet_v2
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - dari_network

volumes:
  postgres_data:

networks:
  dari_network:
    driver: bridge
